name: mplview_env

channels:
  - conda-forge

dependencies:
  - pip==9.0.1
  - wheel==0.29.0
  - coverage==3.7.1
  - python-coveralls==2.5.0

  # Requirements
  - matplotlib==1.5.3
  - npctypes==0.0.2
